# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ServerRPC.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ServerRPC.proto',
  package='Peer2PeerNetwork',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0fServerRPC.proto\x12\x10Peer2PeerNetwork\"\xa6\x01\n\x0b\x44oChatEvent\x12\x11\n\trecipient\x18\x01 \x02(\t\x12\x13\n\x0bsender_uuid\x18\x02 \x02(\t\x12\x13\n\x0bsender_name\x18\x03 \x02(\t\x12\x11\n\tchat_text\x18\x04 \x02(\t\x12\r\n\x05round\x18\x05 \x02(\x05\x12\x0c\n\x04time\x18\x06 \x02(\t\x12\x12\n\nevent_type\x18\x07 \x02(\t\x12\x16\n\x07network\x18\x08 \x01(\x08:\x05\x66\x61lse\"\x1e\n\nEmptyReply\x12\x10\n\x08response\x18\x01 \x02(\t2\\\n\x06Server\x12R\n\x11send_a_chat_event\x12\x1d.Peer2PeerNetwork.DoChatEvent\x1a\x1c.Peer2PeerNetwork.EmptyReply\"\x00'
)




_DOCHATEVENT = _descriptor.Descriptor(
  name='DoChatEvent',
  full_name='Peer2PeerNetwork.DoChatEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='recipient', full_name='Peer2PeerNetwork.DoChatEvent.recipient', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sender_uuid', full_name='Peer2PeerNetwork.DoChatEvent.sender_uuid', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sender_name', full_name='Peer2PeerNetwork.DoChatEvent.sender_name', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='chat_text', full_name='Peer2PeerNetwork.DoChatEvent.chat_text', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='round', full_name='Peer2PeerNetwork.DoChatEvent.round', index=4,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='time', full_name='Peer2PeerNetwork.DoChatEvent.time', index=5,
      number=6, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='event_type', full_name='Peer2PeerNetwork.DoChatEvent.event_type', index=6,
      number=7, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='network', full_name='Peer2PeerNetwork.DoChatEvent.network', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=204,
)


_EMPTYREPLY = _descriptor.Descriptor(
  name='EmptyReply',
  full_name='Peer2PeerNetwork.EmptyReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='response', full_name='Peer2PeerNetwork.EmptyReply.response', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=206,
  serialized_end=236,
)

DESCRIPTOR.message_types_by_name['DoChatEvent'] = _DOCHATEVENT
DESCRIPTOR.message_types_by_name['EmptyReply'] = _EMPTYREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DoChatEvent = _reflection.GeneratedProtocolMessageType('DoChatEvent', (_message.Message,), {
  'DESCRIPTOR' : _DOCHATEVENT,
  '__module__' : 'ServerRPC_pb2'
  # @@protoc_insertion_point(class_scope:Peer2PeerNetwork.DoChatEvent)
  })
_sym_db.RegisterMessage(DoChatEvent)

EmptyReply = _reflection.GeneratedProtocolMessageType('EmptyReply', (_message.Message,), {
  'DESCRIPTOR' : _EMPTYREPLY,
  '__module__' : 'ServerRPC_pb2'
  # @@protoc_insertion_point(class_scope:Peer2PeerNetwork.EmptyReply)
  })
_sym_db.RegisterMessage(EmptyReply)



_SERVER = _descriptor.ServiceDescriptor(
  name='Server',
  full_name='Peer2PeerNetwork.Server',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=238,
  serialized_end=330,
  methods=[
  _descriptor.MethodDescriptor(
    name='send_a_chat_event',
    full_name='Peer2PeerNetwork.Server.send_a_chat_event',
    index=0,
    containing_service=None,
    input_type=_DOCHATEVENT,
    output_type=_EMPTYREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SERVER)

DESCRIPTOR.services_by_name['Server'] = _SERVER

# @@protoc_insertion_point(module_scope)
